vich_uploader:
    db_driver: orm

    mappings:
        image_vins:
            uri_prefix: /images/vins
            upload_destination: '%kernel.project_dir%/public/images/vins'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
